project_id = "grlkbtnwvxorlfglyzid"

[functions.focus-nfe-webhook]
verify_jwt = false

[functions.cora-webhook]
verify_jwt = false

[functions.cora-verificar-pagamentos]
verify_jwt = false

[functions.nf-emissao-data-especifica]
verify_jwt = false

[functions.boleto-emissao-data-especifica]
verify_jwt = false

[functions.emit-nf]
verify_jwt = false

[functions.auto-nf-apos-pagamento]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = true

[functions.emit-boleto-cora]
verify_jwt = true

[functions.send-boleto-cobranca]
verify_jwt = true

[functions.list-users]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.send-user-invite]
verify_jwt = true

[functions.gerar-relatorio-mensal]
verify_jwt = true

[functions.sign-relatorio]
verify_jwt = true

[functions.clicksign-webhook]
verify_jwt = false
