project_id = "grlkbtnwvxorlfglyzid"

[functions.focus-nfe-webhook]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = true

[functions.emit-boleto-cora]
verify_jwt = true

[functions.send-boleto-cobranca]
verify_jwt = true
