/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as DesignPreviewRouteImport } from './routes/design-preview'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppAjudaRouteImport } from './routes/app.ajuda'
import { Route as AppCobrancasRouteImport } from './routes/app.cobrancas'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppFisiosRouteImport } from './routes/app.fisios'
import { Route as AppNotasFiscaisRouteImport } from './routes/app.notas-fiscais'
import { Route as AppPacientesRouteImport } from './routes/app.pacientes'
import { Route as AppProntuarioRouteImport } from './routes/app.prontuario'
import { Route as AppProntuariosRouteImport } from './routes/app.prontuarios'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalContatoRouteImport } from './routes/portal.contato'
import { Route as PortalExerciciosRouteImport } from './routes/portal.exercicios'
import { Route as PortalHistoricoRouteImport } from './routes/portal.historico'
import { Route as PortalLaudosRouteImport } from './routes/portal.laudos'
import { Route as PortalNotasFiscaisRouteImport } from './routes/portal.notas-fiscais'
import { Route as PortalSessoesRouteImport } from './routes/portal.sessoes'
import { Route as AppConfiguracoesIndexRouteImport } from './routes/app.configuracoes.index'
import { Route as AppConfiguracoesConveniosRouteImport } from './routes/app.configuracoes.convenios'
import { Route as AppConfiguracoesCreditosRouteImport } from './routes/app.configuracoes.creditos'
import { Route as AppConfiguracoesInstrumentosRouteImport } from './routes/app.configuracoes.instrumentos'
import { Route as AppConfiguracoesTemplatesRouteImport } from './routes/app.configuracoes.templates'
import { Route as AppPacientesIndexRouteImport } from './routes/app.pacientes.index'
import { Route as AppPacientesPacienteIdRouteImport } from './routes/app.pacientes.$pacienteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignPreviewRoute = DesignPreviewRouteImport.update({
  id: '/design-preview',
  path: '/design-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAjudaRoute = AppAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AppRoute,
} as any)
const AppCobrancasRoute = AppCobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppFisiosRoute = AppFisiosRouteImport.update({
  id: '/fisios',
  path: '/fisios',
  getParentRoute: () => AppRoute,
} as any)
const AppNotasFiscaisRoute = AppNotasFiscaisRouteImport.update({
  id: '/notas-fiscais',
  path: '/notas-fiscais',
  getParentRoute: () => AppRoute,
} as any)
const AppPacientesRoute = AppPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AppRoute,
} as any)
const AppProntuarioRoute = AppProntuarioRouteImport.update({
  id: '/prontuario',
  path: '/prontuario',
  getParentRoute: () => AppRoute,
} as any)
const AppProntuariosRoute = AppProntuariosRouteImport.update({
  id: '/prontuarios',
  path: '/prontuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalContatoRoute = PortalContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => PortalRoute,
} as any)
const PortalExerciciosRoute = PortalExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => PortalRoute,
} as any)
const PortalHistoricoRoute = PortalHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLaudosRoute = PortalLaudosRouteImport.update({
  id: '/laudos',
  path: '/laudos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNotasFiscaisRoute = PortalNotasFiscaisRouteImport.update({
  id: '/notas-fiscais',
  path: '/notas-fiscais',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSessoesRoute = PortalSessoesRouteImport.update({
  id: '/sessoes',
  path: '/sessoes',
  getParentRoute: () => PortalRoute,
} as any)
const AppConfiguracoesIndexRoute = AppConfiguracoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConfiguracoesRoute,
} as any)
const AppConfiguracoesConveniosRoute =
  AppConfiguracoesConveniosRouteImport.update({
    id: '/convenios',
    path: '/convenios',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesCreditosRoute =
  AppConfiguracoesCreditosRouteImport.update({
    id: '/creditos',
    path: '/creditos',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesInstrumentosRoute =
  AppConfiguracoesInstrumentosRouteImport.update({
    id: '/instrumentos',
    path: '/instrumentos',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppConfiguracoesTemplatesRoute =
  AppConfiguracoesTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AppConfiguracoesRoute,
  } as any)
const AppPacientesIndexRoute = AppPacientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPacientesRoute,
} as any)
const AppPacientesPacienteIdRoute = AppPacientesPacienteIdRouteImport.update({
  id: '/$pacienteId',
  path: '/$pacienteId',
  getParentRoute: () => AppPacientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/design-preview': typeof DesignPreviewRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/ajuda': typeof AppAjudaRoute
  '/app/cobrancas': typeof AppCobrancasRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/fisios': typeof AppFisiosRoute
  '/app/notas-fiscais': typeof AppNotasFiscaisRoute
  '/app/pacientes': typeof AppPacientesRouteWithChildren
  '/app/prontuario': typeof AppProntuarioRoute
  '/app/prontuarios': typeof AppProntuariosRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/portal/contato': typeof PortalContatoRoute
  '/portal/exercicios': typeof PortalExerciciosRoute
  '/portal/historico': typeof PortalHistoricoRoute
  '/portal/laudos': typeof PortalLaudosRoute
  '/portal/notas-fiscais': typeof PortalNotasFiscaisRoute
  '/portal/sessoes': typeof PortalSessoesRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/configuracoes/convenios': typeof AppConfiguracoesConveniosRoute
  '/app/configuracoes/creditos': typeof AppConfiguracoesCreditosRoute
  '/app/configuracoes/instrumentos': typeof AppConfiguracoesInstrumentosRoute
  '/app/configuracoes/templates': typeof AppConfiguracoesTemplatesRoute
  '/app/pacientes/$pacienteId': typeof AppPacientesPacienteIdRoute
  '/app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/app/pacientes/': typeof AppPacientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-preview': typeof DesignPreviewRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/ajuda': typeof AppAjudaRoute
  '/app/cobrancas': typeof AppCobrancasRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/fisios': typeof AppFisiosRoute
  '/app/notas-fiscais': typeof AppNotasFiscaisRoute
  '/app/prontuario': typeof AppProntuarioRoute
  '/app/prontuarios': typeof AppProntuariosRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/portal/contato': typeof PortalContatoRoute
  '/portal/exercicios': typeof PortalExerciciosRoute
  '/portal/historico': typeof PortalHistoricoRoute
  '/portal/laudos': typeof PortalLaudosRoute
  '/portal/notas-fiscais': typeof PortalNotasFiscaisRoute
  '/portal/sessoes': typeof PortalSessoesRoute
  '/app': typeof AppIndexRoute
  '/portal': typeof PortalIndexRoute
  '/app/configuracoes/convenios': typeof AppConfiguracoesConveniosRoute
  '/app/configuracoes/creditos': typeof AppConfiguracoesCreditosRoute
  '/app/configuracoes/instrumentos': typeof AppConfiguracoesInstrumentosRoute
  '/app/configuracoes/templates': typeof AppConfiguracoesTemplatesRoute
  '/app/pacientes/$pacienteId': typeof AppPacientesPacienteIdRoute
  '/app/configuracoes': typeof AppConfiguracoesIndexRoute
  '/app/pacientes': typeof AppPacientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/design-preview': typeof DesignPreviewRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/ajuda': typeof AppAjudaRoute
  '/app/cobrancas': typeof AppCobrancasRoute
  '/app/configuracoes': typeof AppConfiguracoesRouteWithChildren
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/fisios': typeof AppFisiosRoute
  '/app/notas-fiscais': typeof AppNotasFiscaisRoute
  '/app/pacientes': typeof AppPacientesRouteWithChildren
  '/app/prontuario': typeof AppProntuarioRoute
  '/app/prontuarios': typeof AppProntuariosRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/portal/contato': typeof PortalContatoRoute
  '/portal/exercicios': typeof PortalExerciciosRoute
  '/portal/historico': typeof PortalHistoricoRoute
  '/portal/laudos': typeof PortalLaudosRoute
  '/portal/notas-fiscais': typeof PortalNotasFiscaisRoute
  '/portal/sessoes': typeof PortalSessoesRoute
  '/app/': typeof AppIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/app/configuracoes/convenios': typeof AppConfiguracoesConveniosRoute
  '/app/configuracoes/creditos': typeof AppConfiguracoesCreditosRoute
  '/app/configuracoes/instrumentos': typeof AppConfiguracoesInstrumentosRoute
  '/app/configuracoes/templates': typeof AppConfiguracoesTemplatesRoute
  '/app/pacientes/$pacienteId': typeof AppPacientesPacienteIdRoute
  '/app/configuracoes/': typeof AppConfiguracoesIndexRoute
  '/app/pacientes/': typeof AppPacientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/design-preview'
    | '/login'
    | '/portal'
    | '/redefinir-senha'
    | '/app/agenda'
    | '/app/ajuda'
    | '/app/cobrancas'
    | '/app/configuracoes'
    | '/app/financeiro'
    | '/app/fisios'
    | '/app/notas-fiscais'
    | '/app/pacientes'
    | '/app/prontuario'
    | '/app/prontuarios'
    | '/app/relatorios'
    | '/app/usuarios'
    | '/portal/contato'
    | '/portal/exercicios'
    | '/portal/historico'
    | '/portal/laudos'
    | '/portal/notas-fiscais'
    | '/portal/sessoes'
    | '/app/'
    | '/portal/'
    | '/app/configuracoes/convenios'
    | '/app/configuracoes/creditos'
    | '/app/configuracoes/instrumentos'
    | '/app/configuracoes/templates'
    | '/app/pacientes/$pacienteId'
    | '/app/configuracoes/'
    | '/app/pacientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-preview'
    | '/login'
    | '/redefinir-senha'
    | '/app/agenda'
    | '/app/ajuda'
    | '/app/cobrancas'
    | '/app/financeiro'
    | '/app/fisios'
    | '/app/notas-fiscais'
    | '/app/prontuario'
    | '/app/prontuarios'
    | '/app/relatorios'
    | '/app/usuarios'
    | '/portal/contato'
    | '/portal/exercicios'
    | '/portal/historico'
    | '/portal/laudos'
    | '/portal/notas-fiscais'
    | '/portal/sessoes'
    | '/app'
    | '/portal'
    | '/app/configuracoes/convenios'
    | '/app/configuracoes/creditos'
    | '/app/configuracoes/instrumentos'
    | '/app/configuracoes/templates'
    | '/app/pacientes/$pacienteId'
    | '/app/configuracoes'
    | '/app/pacientes'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/design-preview'
    | '/login'
    | '/portal'
    | '/redefinir-senha'
    | '/app/agenda'
    | '/app/ajuda'
    | '/app/cobrancas'
    | '/app/configuracoes'
    | '/app/financeiro'
    | '/app/fisios'
    | '/app/notas-fiscais'
    | '/app/pacientes'
    | '/app/prontuario'
    | '/app/prontuarios'
    | '/app/relatorios'
    | '/app/usuarios'
    | '/portal/contato'
    | '/portal/exercicios'
    | '/portal/historico'
    | '/portal/laudos'
    | '/portal/notas-fiscais'
    | '/portal/sessoes'
    | '/app/'
    | '/portal/'
    | '/app/configuracoes/convenios'
    | '/app/configuracoes/creditos'
    | '/app/configuracoes/instrumentos'
    | '/app/configuracoes/templates'
    | '/app/pacientes/$pacienteId'
    | '/app/configuracoes/'
    | '/app/pacientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DesignPreviewRoute: typeof DesignPreviewRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-preview': {
      id: '/design-preview'
      path: '/design-preview'
      fullPath: '/design-preview'
      preLoaderRoute: typeof DesignPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ajuda': {
      id: '/app/ajuda'
      path: '/ajuda'
      fullPath: '/app/ajuda'
      preLoaderRoute: typeof AppAjudaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cobrancas': {
      id: '/app/cobrancas'
      path: '/cobrancas'
      fullPath: '/app/cobrancas'
      preLoaderRoute: typeof AppCobrancasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fisios': {
      id: '/app/fisios'
      path: '/fisios'
      fullPath: '/app/fisios'
      preLoaderRoute: typeof AppFisiosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notas-fiscais': {
      id: '/app/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/app/notas-fiscais'
      preLoaderRoute: typeof AppNotasFiscaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pacientes': {
      id: '/app/pacientes'
      path: '/pacientes'
      fullPath: '/app/pacientes'
      preLoaderRoute: typeof AppPacientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prontuario': {
      id: '/app/prontuario'
      path: '/prontuario'
      fullPath: '/app/prontuario'
      preLoaderRoute: typeof AppProntuarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/prontuarios': {
      id: '/app/prontuarios'
      path: '/prontuarios'
      fullPath: '/app/prontuarios'
      preLoaderRoute: typeof AppProntuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/contato': {
      id: '/portal/contato'
      path: '/contato'
      fullPath: '/portal/contato'
      preLoaderRoute: typeof PortalContatoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/exercicios': {
      id: '/portal/exercicios'
      path: '/exercicios'
      fullPath: '/portal/exercicios'
      preLoaderRoute: typeof PortalExerciciosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/historico': {
      id: '/portal/historico'
      path: '/historico'
      fullPath: '/portal/historico'
      preLoaderRoute: typeof PortalHistoricoRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/laudos': {
      id: '/portal/laudos'
      path: '/laudos'
      fullPath: '/portal/laudos'
      preLoaderRoute: typeof PortalLaudosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/notas-fiscais': {
      id: '/portal/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/portal/notas-fiscais'
      preLoaderRoute: typeof PortalNotasFiscaisRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/sessoes': {
      id: '/portal/sessoes'
      path: '/sessoes'
      fullPath: '/portal/sessoes'
      preLoaderRoute: typeof PortalSessoesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/app/configuracoes/': {
      id: '/app/configuracoes/'
      path: '/'
      fullPath: '/app/configuracoes/'
      preLoaderRoute: typeof AppConfiguracoesIndexRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/convenios': {
      id: '/app/configuracoes/convenios'
      path: '/convenios'
      fullPath: '/app/configuracoes/convenios'
      preLoaderRoute: typeof AppConfiguracoesConveniosRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/creditos': {
      id: '/app/configuracoes/creditos'
      path: '/creditos'
      fullPath: '/app/configuracoes/creditos'
      preLoaderRoute: typeof AppConfiguracoesCreditosRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/instrumentos': {
      id: '/app/configuracoes/instrumentos'
      path: '/instrumentos'
      fullPath: '/app/configuracoes/instrumentos'
      preLoaderRoute: typeof AppConfiguracoesInstrumentosRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/configuracoes/templates': {
      id: '/app/configuracoes/templates'
      path: '/templates'
      fullPath: '/app/configuracoes/templates'
      preLoaderRoute: typeof AppConfiguracoesTemplatesRouteImport
      parentRoute: typeof AppConfiguracoesRoute
    }
    '/app/pacientes/': {
      id: '/app/pacientes/'
      path: '/'
      fullPath: '/app/pacientes/'
      preLoaderRoute: typeof AppPacientesIndexRouteImport
      parentRoute: typeof AppPacientesRoute
    }
    '/app/pacientes/$pacienteId': {
      id: '/app/pacientes/$pacienteId'
      path: '/$pacienteId'
      fullPath: '/app/pacientes/$pacienteId'
      preLoaderRoute: typeof AppPacientesPacienteIdRouteImport
      parentRoute: typeof AppPacientesRoute
    }
  }
}

interface AppConfiguracoesRouteChildren {
  AppConfiguracoesConveniosRoute: typeof AppConfiguracoesConveniosRoute
  AppConfiguracoesCreditosRoute: typeof AppConfiguracoesCreditosRoute
  AppConfiguracoesInstrumentosRoute: typeof AppConfiguracoesInstrumentosRoute
  AppConfiguracoesTemplatesRoute: typeof AppConfiguracoesTemplatesRoute
  AppConfiguracoesIndexRoute: typeof AppConfiguracoesIndexRoute
}

const AppConfiguracoesRouteChildren: AppConfiguracoesRouteChildren = {
  AppConfiguracoesConveniosRoute: AppConfiguracoesConveniosRoute,
  AppConfiguracoesCreditosRoute: AppConfiguracoesCreditosRoute,
  AppConfiguracoesInstrumentosRoute: AppConfiguracoesInstrumentosRoute,
  AppConfiguracoesTemplatesRoute: AppConfiguracoesTemplatesRoute,
  AppConfiguracoesIndexRoute: AppConfiguracoesIndexRoute,
}

const AppConfiguracoesRouteWithChildren =
  AppConfiguracoesRoute._addFileChildren(AppConfiguracoesRouteChildren)

interface AppPacientesRouteChildren {
  AppPacientesPacienteIdRoute: typeof AppPacientesPacienteIdRoute
  AppPacientesIndexRoute: typeof AppPacientesIndexRoute
}

const AppPacientesRouteChildren: AppPacientesRouteChildren = {
  AppPacientesPacienteIdRoute: AppPacientesPacienteIdRoute,
  AppPacientesIndexRoute: AppPacientesIndexRoute,
}

const AppPacientesRouteWithChildren = AppPacientesRoute._addFileChildren(
  AppPacientesRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppAjudaRoute: typeof AppAjudaRoute
  AppCobrancasRoute: typeof AppCobrancasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRouteWithChildren
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFisiosRoute: typeof AppFisiosRoute
  AppNotasFiscaisRoute: typeof AppNotasFiscaisRoute
  AppPacientesRoute: typeof AppPacientesRouteWithChildren
  AppProntuarioRoute: typeof AppProntuarioRoute
  AppProntuariosRoute: typeof AppProntuariosRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppAjudaRoute: AppAjudaRoute,
  AppCobrancasRoute: AppCobrancasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRouteWithChildren,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFisiosRoute: AppFisiosRoute,
  AppNotasFiscaisRoute: AppNotasFiscaisRoute,
  AppPacientesRoute: AppPacientesRouteWithChildren,
  AppProntuarioRoute: AppProntuarioRoute,
  AppProntuariosRoute: AppProntuariosRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalContatoRoute: typeof PortalContatoRoute
  PortalExerciciosRoute: typeof PortalExerciciosRoute
  PortalHistoricoRoute: typeof PortalHistoricoRoute
  PortalLaudosRoute: typeof PortalLaudosRoute
  PortalNotasFiscaisRoute: typeof PortalNotasFiscaisRoute
  PortalSessoesRoute: typeof PortalSessoesRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalContatoRoute: PortalContatoRoute,
  PortalExerciciosRoute: PortalExerciciosRoute,
  PortalHistoricoRoute: PortalHistoricoRoute,
  PortalLaudosRoute: PortalLaudosRoute,
  PortalNotasFiscaisRoute: PortalNotasFiscaisRoute,
  PortalSessoesRoute: PortalSessoesRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DesignPreviewRoute: DesignPreviewRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
